### ISSUE TITLE
Optional Arguments (e.g. SPINDOWN_TIME)

### ISSUE THREAD

**Issue by hhergeth** [fightforlife/docker_hddfancontrol#2]
Is it possible to not use the spindown feature? I tried leaving the env variable SPINDOWN_TIME empty but that produces an error from hddfancontrol because the docker entry script tries to pass a value. The same applies to the log file.

Furthermore it would be great if passing smartctl would be optional because if I understand the code [here](https://github.com/desbma/hddfancontrol/blob/8544c662e5a17ddde81ea95210388c1a6b07fbfa/hddfancontrol/__init__.py#L147) correctly this makes it impossible to use the new drivetemp kernel module based mode for fetching the temperature.

**Comment by fightforlife** [comment]
Hi @hhergeth, please check out the dev branch.
`fred92/hddfancontrol:dev`
[dev- start_services.sh](https://github.com/fightforlife/docker_hddfancontrol/blob/dev/start_services.sh)
I just commited some changes there:

1. all parameters are now optional, if any required argument is missing hddfancontrol will complain in the logs.
2. I created a new parameter `$TEMP_QUERY_MODE` which should take one of the following values (hddtemp  hdparm smartctl drivetemp), or can be left empty for the default.

If it works for you as expected I would merge it into master and create a new version. Thanks!

**Comment by hhergeth** [comment]
Hey thanks so much for implementing this!
I just tested it and it works like a charm :)

**Comment by fightforlife** [comment]
Thank you for the feedback!
Just merged the dev changes into master and created a new persisted tag v0.5.0.

In the future fred92/hddfancontrol:master or fred92/hddfancontrol:v0.5.0 should be used.
