### ISSUE TITLE
[BUG] Missing /dev/disk/*

### ISSUE THREAD

**Issue by anto294** [fightforlife/docker_hddfancontrol#9]
Hello,
I have been using this container for months and it works excellently.
However, as known, every reboot of linux "/dev/sd*" changes.
Having an m.2 sata disk, I need not to monitor it, as it reports high and wrong temperature.
Wanting to use persistent parameters, such as /dev/disk/by-id, the container goes "no such file or directory: '/dev/disk/by-id/***'" error.

I solved by mounting the /dev volume on the container '/dev:/dev:ro'
However, a cleaner solution valid for all use cases would be better (I use it on TrueNAS Scale)

**Comment by fightforlife** [comment]
Thank you for the hint! I do not have a solution for now but I will add this as a hint to the readme.
